const directoryPath = '/backend/src/assets/heroes';

export const heroes = [
    {
        name: 'Abbadon',
        icon: directoryPath + '/abbadon.png',
        attribute: 'universal',
        roles: ['1', '3', '4', '5'],
        id: '',
    },
    {
        name: 'Alchemist',
        icon: directoryPath + '/alchemist.png',
        attribute: 'strength',
        roles: ['1', '2', '3'],
        id: '',
    },
    {
        name: 'Ancient Apparition',
        icon: directoryPath + '/ancient_apparition.png',
        attribute: 'intelligence',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Anti-Mage',
        icon: directoryPath + '/anti_mage.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Arc Warden',
        icon: directoryPath + '/arc_warden.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Axe',
        icon: directoryPath + '/axe.png',
        attribute: 'strength',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Bane',
        icon: directoryPath + '/bane.png',
        attribute: 'universal',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Batrider',
        icon: directoryPath + '/batrider.png',
        attribute: 'universal',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Beastmaster',
        icon: directoryPath + '/beastmaster.png',
        attribute: 'universal',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Bloodseeker',
        icon: directoryPath + '/bloodseeker.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Bounty Hunter',
        icon: directoryPath + '/bounty_hunter.png',
        attribute: 'agility',
        roles: ['2', '3', '4'],
        id: '',
    },
    {
        name: 'Brewmaster',
        icon: directoryPath + '/brewmaster.png',
        attribute: 'universal',
        roles: ['2', '3', '4'],
        id: '',
    },
    {
        name: 'Bristleback',
        icon: directoryPath + '/bristleback.png',
        attribute: 'strength',
        roles: ['1', '3'],
        id: '',
    },
    {
        name: 'Broodmother',
        icon: directoryPath + '/broodmother.png',
        attribute: 'universal',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Centaur Warrunner',
        icon: directoryPath + '/centaur_warrunner.png',
        attribute: 'strength',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Chaos Knight',
        icon: directoryPath + '/chaos_knight.png',
        attribute: 'strength',
        roles: ['1', '3'],
        id: '',
    },
    {
        name: 'Chen',
        icon: directoryPath + '/chen.png',
        attribute: 'universal',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Clinkz',
        icon: directoryPath + '/clinkz.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Clockwerk',
        icon: directoryPath + '/clockwerk.png',
        attribute: 'universal',
        roles: ['3', '4', '5'],
        id: '',
    },
    {
        name: 'Crystal Maiden',
        icon: directoryPath + '/crystal_maiden.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Dark Seer',
        icon: directoryPath + '/dark_seer.png',
        attribute: 'universal',
        roles: ['3', '4'],
        id: '',
    },
    {
        name: 'Dark Willow',
        icon: directoryPath + '/dark_willow.png',
        attribute: 'universal',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Dawnbreaker',
        icon: directoryPath + '/dawnbreaker.png',
        attribute: 'strength',
        roles: ['3', '4', '5'],
        id: '',
    },
    {
        name: 'Dazzle',
        icon: directoryPath + '/dazzle.png',
        attribute: 'universal',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Death Prophet',
        icon: directoryPath + '/death_prophet.png',
        attribute: 'intelligence',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Disruptor',
        icon: directoryPath + '/disruptor.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Doom',
        icon: directoryPath + '/doom.png',
        attribute: 'strength',
        roles: ['2', '3', '4'],
        id: '',
    },
    {
        name: 'Dragon Knight',
        icon: directoryPath + '/dragon_knight.png',
        attribute: 'strength',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Drow Ranger',
        icon: directoryPath + '/drow_ranger.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Earth Spirit',
        icon: directoryPath + '/earth_spirit.png',
        attribute: 'strength',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Earthshaker',
        icon: directoryPath + '/earthshaker.png',
        attribute: 'strength',
        roles: ['3', '4'],
        id: '',
    },
    {
        name: 'Elder Titan',
        icon: directoryPath + '/elder_titan.png',
        attribute: 'strength',
        roles: ['3', '4', '5'],
        id: '',
    },
    {
        name: 'Ember Spirit',
        icon: directoryPath + '/ember_spirit.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Enchantress',
        icon: directoryPath + '/enchantress.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Enigma',
        icon: directoryPath + '/enigma.png',
        attribute: 'universal',
        roles: ['3', '4'],
        id: '',
    },
    {
        name: 'Faceless Void',
        icon: directoryPath + '/faceless_void.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Grimstroke',
        icon: directoryPath + '/grimstroke.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Gyrocopter',
        icon: directoryPath + '/gyrocopter.png',
        attribute: 'agility',
        roles: ['1', '2', '4', '5'],
        id: '',
    },
    {
        name: 'Hoodwink',
        icon: directoryPath + '/hoodwink.png',
        attribute: 'agility',
        roles: ['2', '3', '4'],
        id: '',
    },
    {
        name: 'Huskar',
        icon: directoryPath + '/huskar.png',
        attribute: 'strength',
        roles: ['2'],
        id: '',
    },
    {
        name: 'Invoker',
        icon: directoryPath + '/invoker.png',
        attribute: 'intelligence',
        roles: ['2', '4'],
        id: '',
    },
    {
        name: 'Io',
        icon: directoryPath + '/io.png',
        attribute: 'universal',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Jakiro',
        icon: directoryPath + '/jakiro.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Juggernaut',
        icon: directoryPath + '/juggernaut.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Keeper of the Light',
        icon: directoryPath + '/keeper_of_the_light.png',
        attribute: 'intelligence',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Kunkka',
        icon: directoryPath + '/kunkka.png',
        attribute: 'strength',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Legion Commander',
        icon: directoryPath + '/legion_commander.png',
        attribute: 'strength',
        roles: ['1', '2', '3'],
        id: '',
    },
    {
        name: 'Leshrac',
        icon: directoryPath + '/leshrac.png',
        attribute: 'intelligence',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Lich',
        icon: directoryPath + '/lich.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Lifestealer',
        icon: directoryPath + '/lifestealer.png',
        attribute: 'strength',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Lina',
        icon: directoryPath + '/lina.png',
        attribute: 'intelligence',
        roles: ['2'],
        id: '',
    },
    {
        name: 'Lion',
        icon: directoryPath + '/lion.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Lone Druid',
        icon: directoryPath + '/lone_druid.png',
        attribute: 'universal',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Luna',
        icon: directoryPath + '/luna.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Lycan',
        icon: directoryPath + '/lycan.png',
        attribute: 'universal',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Magnus',
        icon: directoryPath + '/magnus.png',
        attribute: 'universal',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Marci',
        icon: directoryPath + '/marci.png',
        attribute: 'universal',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Mars',
        icon: directoryPath + '/mars.png',
        attribute: 'strength',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Medusa',
        icon: directoryPath + '/medusa.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Meepo',
        icon: directoryPath + '/meepo.png',
        attribute: 'agility',
        roles: ['2'],
        id: '',
    },
    {
        name: 'Mirana',
        icon: directoryPath + '/mirana.png',
        attribute: 'universal',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Monkey King',
        icon: directoryPath + '/monkey_king.png',
        attribute: 'agility',
        roles: ['1', '2', '4'],
        id: '',
    },
    {
        name: 'Morphling',
        icon: directoryPath + '/morphling.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Muerta',
        icon: directoryPath + '/muerta.png',
        attribute: 'intelligence',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Naga Siren',
        icon: directoryPath + '/naga_siren.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Natures Prophet',
        icon: directoryPath + '/natures_prophet.png',
        attribute: 'intelligence',
        roles: ['2', '3', '4'],
        id: '',
    },
    {
        name: 'Necrophos',
        icon: directoryPath + '/necrophos.png',
        attribute: 'intelligence',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Night Stalker',
        icon: directoryPath + '/night_stalker.png',
        attribute: 'strength',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Nyx Assassin',
        icon: directoryPath + '/nyx_assassin.png',
        attribute: 'universal',
        roles: ['2', '4'],
        id: '',
    },
    {
        name: 'Ogre Magi',
        icon: directoryPath + '/ogre_magi.png',
        attribute: 'strength',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Omniknight',
        icon: directoryPath + '/omniknight.png',
        attribute: 'strength',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Oracle',
        icon: directoryPath + '/oracle.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Outworld Destroyer',
        icon: directoryPath + '/outworld_destroyer.png',
        attribute: 'intelligence',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Pangolier',
        icon: directoryPath + '/pangolier.png',
        attribute: 'universal',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Phantom Assassin',
        icon: directoryPath + '/phantom_assassin.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Phantom Lancer',
        icon: directoryPath + '/phantom_lancer.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Phoenix',
        icon: directoryPath + '/phoenix.png',
        attribute: 'universal',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Primal Beast',
        icon: directoryPath + '/primal_beast.png',
        attribute: 'strength',
        roles: ['2', '3', '4'],
        id: '',
    },
    {
        name: 'Puck',
        icon: directoryPath + '/puck.png',
        attribute: 'intelligence',
        roles: ['2'],
        id: '',
    },
    {
        name: 'Pudge',
        icon: directoryPath + '/pudge.png',
        attribute: 'strength',
        roles: ['2', '4'],
        id: '',
    },
    {
        name: 'Pugna',
        icon: directoryPath + '/pugna.png',
        attribute: 'intelligence',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Queen of Pain',
        icon: directoryPath + '/queen_of_pain.png',
        attribute: 'intelligence',
        roles: ['2', '4'],
        id: '',
    },
    {
        name: 'Razor',
        icon: directoryPath + '/razor.png',
        attribute: 'agility',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Riki',
        icon: directoryPath + '/riki.png',
        attribute: 'agility',
        roles: ['1', '2', '4'],
        id: '',
    },
    {
        name: 'Rubick',
        icon: directoryPath + '/rubick.png',
        attribute: 'intelligence',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Sand King',
        icon: directoryPath + '/sand_king.png',
        attribute: 'universal',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Shadow Demon',
        icon: directoryPath + '/shadow_demon.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Shadow Fiend',
        icon: directoryPath + '/shadow_fiend.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Shadow Shaman',
        icon: directoryPath + '/shadow_shaman.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Silencer',
        icon: directoryPath + '/silencer.png',
        attribute: 'intelligence',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Skywrath Mage',
        icon: directoryPath + '/skywrath_mage.png',
        attribute: 'intelligence',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Slardar',
        icon: directoryPath + '/slardar.png',
        attribute: 'strength',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Slark',
        icon: directoryPath + '/slark.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Snapfire',
        icon: directoryPath + '/snapfire.png',
        attribute: 'universal',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Sniper',
        icon: directoryPath + '/sniper.png',
        attribute: 'agility',
        roles: ['1', '2', '4'],
        id: '',
    },
    {
        name: 'Spectre',
        icon: directoryPath + '/spectre.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Spirit Breaker',
        icon: directoryPath + '/spirit_breaker.png',
        attribute: 'strength',
        roles: ['4'],
        id: '',
    },
    {
        name: 'Storm Spirit',
        icon: directoryPath + '/storm_spirit.png',
        attribute: 'intelligence',
        roles: ['2'],
        id: '',
    },
    {
        name: 'Sven',
        icon: directoryPath + '/sven.png',
        attribute: 'strength',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Techies',
        icon: directoryPath + '/techies.png',
        attribute: 'universal',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Templar Assassin',
        icon: directoryPath + '/templar_assassin.png',
        attribute: 'agility',
        roles: ['1', '2'],
        id: '',
    },
    {
        name: 'Terrorblade',
        icon: directoryPath + '/terrorblade.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Tidehunter',
        icon: directoryPath + '/tidehunter.png',
        attribute: 'strength',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Timbersaw',
        icon: directoryPath + '/timbersaw.png',
        attribute: 'universal',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Tinker',
        icon: directoryPath + '/tinker.png',
        attribute: 'intelligence',
        roles: ['2'],
        id: '',
    },
    {
        name: 'Tiny',
        icon: directoryPath + '/tiny.png',
        attribute: 'strength',
        roles: ['1', '2', '3', '4'],
        id: '',
    },
    {
        name: 'Treant Protector',
        icon: directoryPath + '/treant_protector.png',
        attribute: 'strength',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Troll Warlord',
        icon: directoryPath + '/troll_warlord.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Tusk',
        icon: directoryPath + '/tusk.png',
        attribute: 'strength',
        roles: ['2', '3', '4'],
        id: '',
    },
    {
        name: 'Underlord',
        icon: directoryPath + '/underlord.png',
        attribute: 'strength',
        roles: ['3'],
        id: '',
    },
    {
        name: 'Undying',
        icon: directoryPath + '/undying.png',
        attribute: 'strength',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Ursa',
        icon: directoryPath + '/ursa.png',
        attribute: 'agility',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Vengeful Spirit',
        icon: directoryPath + '/vengeful_spirit.png',
        attribute: 'universal',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Venomancer',
        icon: directoryPath + '/venomancer.png',
        attribute: 'universal',
        roles: ['3', '4', '5'],
        id: '',
    },
    {
        name: 'Viper',
        icon: directoryPath + '/viper.png',
        attribute: 'agility',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Visage',
        icon: directoryPath + '/visage.png',
        attribute: 'universal',
        roles: ['2', '3'],
        id: '',
    },
    {
        name: 'Void Spirit',
        icon: directoryPath + '/void_spirit.png',
        attribute: 'universal',
        roles: ['2'],
        id: '',
    },
    {
        name: 'Warlock',
        icon: directoryPath + '/warlock.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Weaver',
        icon: directoryPath + '/weaver.png',
        attribute: 'agility',
        roles: ['1', '4'],
        id: '',
    },
    {
        name: 'Windranger',
        icon: directoryPath + '/windranger.png',
        attribute: 'universal',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Winter Wyvern',
        icon: directoryPath + '/winter_wyvern.png',
        attribute: 'universal',
        roles: ['2', '4', '5'],
        id: '',
    },
    {
        name: 'Witch Doctor',
        icon: directoryPath + '/witch_doctor.png',
        attribute: 'intelligence',
        roles: ['4', '5'],
        id: '',
    },
    {
        name: 'Wraith King',
        icon: directoryPath + '/wraith_king.png',
        attribute: 'strength',
        roles: ['1'],
        id: '',
    },
    {
        name: 'Zeus',
        icon: directoryPath + '/zeus.png',
        attribute: 'intelligence',
        roles: ['2', '4'],
        id: '',
    },
];
